services:
  - type: web
    name: n8n-service
    runtime: docker
    plan: free

    image:
      url: docker.io/n8nio/n8n:latest

    ports:
      - port: 5678

    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-cvl846fgi27c73dlbms0-a.render.com
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_free
      - key: DB_POSTGRESDB_USER
        value: n8n_free_user
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin
