# An excerpt from render.yaml
services:
  - type: web
    name: n8n-service
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME  # <-- Replace with your actual repo
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-cvl846fgi27c73dlbms0-a.render.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_free
      - key: DB_POSTGRESDB_USER
        value: n8n_free_user
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin
