# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-cvl846fgi27c73dlbms0-a.render.com
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_free
      - key: DB_POSTGRESDB_USER
        value: n8n_free_user
      - key: DB_POSTGRESDB_PASSWORD
        sync: false  # Add the actual password in the Render dashboard
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin

    plan: free  # Tells Render to use the free tier

# OPTIONAL: Remove the block below if you already have a PostgreSQL database created in Render
# databases:
#   - name: n8n-db
#     plan: free
#     # diskSizeGB: 5
